---
title: "Comparing Students' Grades"
author: "Jay Ralyea, William Cull, and John Hope"
date: "5/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) # whole bunch of useful packages
library(tidymodels)
library(modelr)
library(randomForest) # builds random forest models
library(caret) # builds models and partitions data
library(viridis)
```



```{r}
## Load in the data
math <- read_csv("student-mat.csv")
por <- read_csv("student-por.csv")

## Data exploration
quantile(math$G3)
quantile(por$G3)

## Percent zeros
table(math$G3)[1] / nrow(math)
table(por$G3)[1] / nrow(por)

## Factor variables in each dataset
factors <- c("school", "sex", "address", "famsize", "Pstatus", "Medu",
             "Fedu", "Mjob", "Fjob", "reason", "guardian", "traveltime",
             "studytime", "failures", "schoolsup", "famsup", "paid",
             "activities", "nursery", "higher", "internet", "romantic")

math[factors] <- sapply(math[factors], as.factor)
por[factors] <- sapply(por[factors], as.factor)

## Remove G1 and G2 grades (determine G3 grade)
math <- math %>%
  select(-G1, -G2)
por <- por %>%
  select(-G1, -G2)

## Change the G3 score to be poor, good, or excellent
math$G3 <- cut(math$G3,
                   breaks = c(-Inf, 8, 13, Inf),
                   labels = c("poor", "good", "excellent"))
por$G3 <- cut(por$G3,
                  breaks = c(-Inf, 10, 13, Inf),
                  labels = c("poor", "good", "excellent"))
  
```


# EDA
```{r}
# School
math %>%
  ggplot(aes(x = school, fill = G3)) + 
  geom_bar(position = "dodge") +
  scale_fill_viridis_d() +
  theme_bw() +
  labs(title = "Distirbution of Math G3 Scores by School", 
       x = "School", y = "Count of Scores", fill = "G3 Score") +
  scale_x_discrete(labels = c("GP" = "Gabriel Pereira", 
                              "MS" = "Mouzinho da Silveira"))

por %>%
  ggplot(aes(x = school, fill = G3)) + 
  geom_bar(position = "dodge") +
  scale_fill_viridis_d() +
  theme_bw() +
  labs(title = "Distirbution of Portuguese G3 Scores by School", 
       x = "School", y = "Count of Scores", fill = "G3 Score") +
  scale_x_discrete(labels = c("GP" = "Gabriel Pereira", 
                              "MS" = "Mouzinho da Silveira"))
```

```{r}
# Gender
math %>%
  ggplot(aes(x = G3, fill = G3)) + 
  geom_bar() + facet_grid(cols = vars(sex)) +
  scale_fill_viridis_d() +
  theme_bw()

por %>%
  ggplot(aes(x = G3, fill = G3)) + 
  geom_bar() + facet_grid(cols = vars(sex)) +
  scale_fill_viridis_d() +
  theme_bw()
```

```{r}
# Age
math %>%
  ggplot(aes(x = age, fill = G3)) + 
  geom_bar(position = "dodge") +
  scale_fill_viridis_d() + 
  theme_bw() +
  scale_x_continuous(breaks = seq(15, 22, 1)) +
  theme(panel.grid.minor.x = element_blank())

por %>%
  ggplot(aes(x = age, fill = G3)) + 
  geom_bar(position = "dodge") +
  scale_fill_viridis_d() + 
  theme_bw() +
  scale_x_continuous(breaks = seq(15, 22, 1)) +
  theme(panel.grid.minor.x = element_blank())
```

```{r}
# Family size
math %>%
  ggplot(aes(x = famsize, fill = G3)) + 
  geom_bar(position = "dodge") +
  scale_fill_viridis_d() +
  theme_bw() +
  labs(title = "Distirbution of Math G3 Scores by Family Size",
       y = "Count of Scores", x = "Family Size", fill = "G3 Score") +
  scale_x_discrete(labels = c("GT3" = "Greater than 3",
                              "LE3" = "Less than or equal to 3"))

por %>%
  ggplot(aes(x = famsize, fill = G3)) + 
  geom_bar(position = "dodge") +
  scale_fill_viridis_d() +
  theme_bw() +
  labs(title = "Distirbution of Portuguese G3 Scores by Family Size",
       y = "Count of Scores", x = "Family Size", fill = "G3 Score") +
  scale_x_discrete(labels = c("GT3" = "Greater than 3",
                              "LE3" = "Less than or equal to 3"))
```


```{r}
# Parental job - Math
math %>%
  ggplot(aes(x = Mjob, fill = G3)) + 
  geom_bar(position = "dodge") + 
  scale_fill_viridis_d() +
  labs(title = "Distribution of Math G3 Scores by Mother's Job",
       x = "Mother's Job", y = "Count of Score", fill = "G3 Score") +
  theme_bw()

math %>%
  ggplot(aes(x = Fjob, fill = G3)) + 
  geom_bar(position = "dodge") + 
  scale_fill_viridis_d() +
  labs(title = "Distribution of Math G3 Scores by Father's Job",
       x = "Father's Job", y = "Count of Score", fill = "G3 Score") +
  theme_bw()
```


```{r}
# Parental job - Portuguese
por %>%
  ggplot(aes(x = Mjob, fill = G3)) + 
  geom_bar(position = "dodge") + 
  scale_fill_viridis_d() +
  labs(title = "Distribution of Math G3 Scores by Mother's Job",
       x = "Mother's Job", y = "Count of Score", fill = "G3 Score") +
  theme_bw()

por %>%
  ggplot(aes(x = Fjob, fill = G3)) + 
  geom_bar(position = "dodge") + 
  scale_fill_viridis_d() +
  labs(title = "Distribution of Math G3 Scores by Father's Job",
       x = "Father's Job", y = "Count of Score", fill = "G3 Score") +
  theme_bw()
```

```{r}
# Address
math %>%
  ggplot(aes(x = address, y = G3, fill = address)) + 
  geom_bar(stat = "summary", fun.y = "mean") +
  scale_fill_viridis_d() + 
  theme_bw() + 
  labs(title = "Mean G3 Score for Different Addresses", 
       x = "Address Location", y = "Mean G3 Score", fill = "Address Location")

por %>%
  ggplot(aes(x = address, y = G3, fill = address)) + 
  geom_bar(stat = "summary", fun.y = "mean") +
  scale_fill_viridis_d() + 
  theme_bw() + 
  labs(title = "Mean G3 Score for Different Addresses", 
       x = "Address Location", y = "Mean G3 Score", fill = "Address Location")

```








```{r}
## Split the data for model building

## Create the partition
set.seed(2000) # ensure reproducibility
math.part <- createDataPartition(math$G3, times=1, p=0.8, list=FALSE)
set.seed(2000) # ensure reproducibility
por.part <- createDataPartition(por$G3, times=1, p=0.8, list = FALSE)

## Math training and testing data
math.training <- math[math.part,]
math.test <- math[-math.part,]

## Portuguese training and testing data
por.training <- por[por.part,]
por.test <- por[-por.part,]
```



































